apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  database: {{ .Values.auth.database }}
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}