-- Initialize schemas for microservices

-- Create schemas for each service
CREATE SCHEMA IF NOT EXISTS authentication_service;
CREATE SCHEMA IF NOT EXISTS user_service;
CREATE SCHEMA IF NOT EXISTS peaks_hikes_service;
CREATE SCHEMA IF NOT EXISTS trail_import_service;
CREATE SCHEMA IF NOT EXISTS weather_service;
CREATE SCHEMA IF NOT EXISTS social_feed_service;
CREATE SCHEMA IF NOT EXISTS badge_service;
CREATE SCHEMA IF NOT EXISTS scoreboards_challenges_service;
CREATE SCHEMA IF NOT EXISTS activity_service;
CREATE SCHEMA IF NOT EXISTS notification_service;



-- Set default privileges for future tables (this applies to tables created AFTER this)
ALTER DEFAULT PRIVILEGES IN SCHEMA authentication_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA peaks_hikes_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA trail_import_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA weather_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA social_feed_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA badge_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA scoreboards_challenges_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA activity_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

-- Grant permissions on sequences (for auto-increment IDs)
ALTER DEFAULT PRIVILEGES IN SCHEMA authentication_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA peaks_hikes_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA trail_import_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA weather_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA social_feed_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA badge_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA scoreboards_challenges_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA activity_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;

-- Enable useful extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
