kumuluzee:
  name: authentication-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8081
  datasources:
    default:
      connectionUrl: jdbc:postgresql://postgres.database.svc.cluster.local:5432/hikudb
      username: hikuuser
      password: hikupassword