apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authentication-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentication-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authentication-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authentication-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: authentication-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.clusterIP.port }}